#main pipeline
name: end to end pipline with security

on: 
    push: 
        
jobs: 
    code-qualiy: 
        uses: ./.github/workflows/lint.yml      
        
    git-leaks:
        uses: ./.github/workflows/gitleaks-scan.yml    
          

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

     

    sonar-scan:
        uses: ./.github/workflows/sonarqube-scan.yml
        secrets: inherit   

    docker-scan:
        uses: ./.github/workflows/docker-scans.yml 
        secrets: inherit  
        
        
    docker-build-push:
        uses: ./.github/workflows/image-push.yml
        secrets: inherit
        needs: [docker-scan, sonar-scan]
    
    
    
