name: Docker Scan
on: 
    workflow_dispatch: 
jobs: 
    docker-scan: 
        runs-on: ubuntu-latest
        strategy:
            matrix:
                image: [ "frontend", "backend" ]
        steps: 
            - name: code checkout
              uses: actions/checkout@v7
              
            - name: hadolint scan 
              uses: hadolint/hadolint-action@v3.1.0
              with: 
                dockerfile: ${{ matrix.image}}/Dockerfile

            - name: docker login
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                
            - name: docker build ${{ matrix.image}}
              run: docker build -t ${{ vars.DOCKER_USERNAME}}/university-${{ matrix.image}}:LATEST .
              working-directory: ${{ matrix.image}}
                            
            - name: trivy scan
              continue-on-error: true
              uses: aquasecurity/trivy-action@v0.36.0
              with: 
                image-ref: ${{ vars.DOCKER_USERNAME}}/university-${{ matrix.image}}:LATEST
                format: 'table'
                ignore-unfixed: true
                exit-code: 1
                vuln-type: 'os,library'
                severity: 'CRITICAL'
